// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { MapConfig } from "./tables/MapConfig.sol";
import { Food } from "./tables/Food.sol";
import { Movable } from "./tables/Movable.sol";
import { Obstruction } from "./tables/Obstruction.sol";
import { Player } from "./tables/Player.sol";
import { HeadDirection } from "./tables/HeadDirection.sol";
import { Snake } from "./tables/Snake.sol";
import { SnakeLength } from "./tables/SnakeLength.sol";
import { Position } from "./tables/Position.sol";
