// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Direction } from "./../common.sol";

/**
 * @title IMapSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IMapSystem {
  function spawn(int32 x, int32 y) external;

  function eatFood(bytes32 player, int32 x, int32 y) external;

  function spawnFood() external;

  function eatFlag(bytes32 player, int32 x, int32 y) external;

  function spawnFlag() external;

  function setPlayerDirection(Direction direction) external;

  function move() external;
}
